---
- name: Restore router configurations from archive
  hosts: cisco
  connection: network_cli
  gather_facts: no
  vars_files:
    default_vars.yml

  tasks:

  - name: clone configuration archives to ansible control
    git:
      repo: "{{ git_repo_path}}"
      dest: "{{ playbook_dir}}/ios-config-archives"
      clone: yes
      force: yes
    run_once: yes
    delegate_to: localhost

  - name: Copy archived config to router
    net_put:
      src: "{{playbook_dir}}/ios-config-archives/{{inventory_hostname}}.cfg"
      dest: "flash:{{inventory_hostname}}.config"

  - name: config replace
    ios_command:
      commands:
        - "config replace flash:{{inventory_hostname}}.config force"
