---
- name: Restore router configurations from archive
  hosts: cisco
  connection: network_cli
  gather_facts: no
  vars_files:
    default_vars.yml

  tasks:

  - name: Copy archived config to router and config replace
    include_role:
      name: ansible-network.config_manager
      tasks_from: load
    vars:
      config_manager_scm_url: "{{ git_repo_path }}"
      config_manager_replace: True
    delegate_to: localhost
