---
- name: Check for OOB config changes
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:

  - name: ENSURE THAT THE DIR TO STORE RUNNING CONFIGS EXITS
    file:
      path: "{{ playbook_dir }}/files/running_configs"
      state: directory
      mode: 0777
    delegate_to: localhost
    run_once: yes


  - name: GET THE RUNNING CONFIG OF THE DEVICES
    ios_command:
      commands:
        - show running-config
    register: running_config

  - name: SAVE THE RUNNING CONFIG LOCALLY
    template:
      src: render_running.j2
      dest: "{{ playbook_dir }}/files/running_configs/{{ inventory_hostname }}.cfg"


  - name: SANITIZE THE RUNNING CONFIGS
    lineinfile:
      regexp: "! Last configuration .*"
      path: "{{ playbook_dir }}/files/running_configs/{{ inventory_hostname }}.cfg"
      state: absent

  - name: REMOVE NON CONFIG LINES
    lineinfile:
      path: "{{ playbook_dir }}/files/running_configs/{{ inventory_hostname }}.cfg"
      line: "Building configuration..."
      state: absent

  - name: REMOVE NON CONFIG LINES - REGEXP
    lineinfile:
      path: "{{ playbook_dir }}/files/running_configs/{{ inventory_hostname }}.cfg"
      regexp: 'Current configuration.*'
      state: absent



  - name: CHECK IF OOB CHANGES EXIST
    command: >-
      diff "{{ playbook_dir }}"/files/running_configs "{{ playbook_dir }}"/files/repo_dir
    register: difference
    failed_when: difference.rc > 1
    changed_when: difference.rc == 1
    delegate_to: localhost
    run_once: true

  - name: DISPLAY DIFFERENCES
    debug:
      var: difference.stdout
    when: difference.rc != 0
    delegate_to: localhost
    run_once: true

  - name: GENERATE DIFF REPORT
    template:
      src: diff_report.j2
      dest: "{{ playbook_dir }}/files/diff_report.txt"

  - name: OOB CHANGES DETECTED
    assert:
      that: difference.rc == 0
      msg: "Caretaker has identified an OOB change on your network. Manual sync required... Aborting deployment."

  - name: END PLAY
    meta: end_play
